### ISSUE TITLE
Components for Milestone 1

### ISSUE THREAD

**Issue by cuteolaf** [TheDotflow/dotflow-ui#2]
- [x] Connect/Disconnect wallet
- [x] Connect to network
- [x] Create identity
- [x] Remove identity
- [x] Show addresses
- [x] Add address
- [x] Update address
- [x] Remove address
- [x] Generate `IdentityKey`
- [x] Share Identity Key
- [x] Import Identity Key
